# docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql8-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mars_user
      MYSQL_PASSWORD: mars_password
      MYSQL_DATABASE: mars
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev-net

volumes:
  db_data:

networks:
  dev-net:
