### create user
POST http://localhost:4000/users
Content-Type: application/json

{
    "email":"elon@mars.com",
    "password":"wegomars",
    "nick":"doge1"
}

### get user by email
GET http://localhost:3000/users?email=elon2@mars.com

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"2elon@mars.com",
    "password":"wegomars"
}

### whoami
GET http://localhost:3000/users/whoami