@host = http://localhost:4000/api

### Request : Get stock list
GET {{host}}/stocks/symbols

### Request : Get Chart with variables
@symbol = AAPL
@interval = 1h
@limit = 2
GET {{host}}/stocks/chart?symbol={{symbol}}&interval={{interval}}&limit={{limit}}

### Request : get Detailed Stock data
@symbol = AAPL
GET {{host}}/stocks/{{symbol}}

### Request : search stocks by symbol and name
@query = A
@limit = 2
GET {{host}}/stocks/search?query={{query}}&limit={{limit}}