@host = http://localhost:4000

### Request : Get stock list
GET {{host}}/stocks/symbols

### Request : Get Chart with variables
@symbol = AAPL
@interval = 1h
@limit = 2
GET {{host}}/stocks/chart?symbol={{symbol}}&interval={{interval}}&limit={{limit}}

### Request : get Detailed Stock data
@symbol = AAPd
GET {{host}}/stocks/{{symbol}}
