@host = http://localhost:4000/api

### Request : sign up
POST {{host}}/users/
Content-Type: application/json

{
  "email": "elon5@mars.com",
  "password": "wegomars",
  "nick": "doge1"
}

### Request : sign in
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "elon5@mars.com",
  "password": "wegomars"
}
######################################################################
### create user preference
POST {{host}}/ai/preference
Content-Type: application/json

{
  "riskLevel": "high",
  "preferredStrategies": ["dividend_stability", "portfolio_balance", "value_stability", "rebound_buy"],
  "preferredSectors" : ["Basic Materials"]
}