name: Deploy Backend on Main Push

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Prepare build directory
        run: |
          mkdir build
          cp -r dist build/
          cp package.json package-lock.json build/

      - name: Clean server build directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          script: |
            rm -rf ~/infra/backend/build/*

      - name: Copy build artifacts to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          source: "build/*"
          target: "~/infra/backend"

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          script: |
            cd ~/infra
            docker compose down
            docker builder prune -af     
            docker image prune -af       
            docker compose up -d --build
